### ISSUE TITLE
Optimise render method

### ISSUE THREAD

**Issue by noway** [vaxxnz/vaxxnz#115]
**Describe the bug**
Our site is getting a bit laggy. We do a lot of data processing in render method - we should memoize it as much as possible.

**To Reproduce**
1. Go to website
2. Open React Profiler
3. Start profiling
4. Open a modal
5. Observe long-running renders

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/132857085-b72bf979-b03c-405b-8ee6-0ad6ad755bda.png)

**Additional context**
We need to useMemo a bunch of variables. especially when we do .sort, .filter and .reduce.
![image](https://user-images.githubusercontent.com/2031472/132858124-01a30339-a357-4665-b276-55d616528261.png)

**Comment by noway** [comment]
Partly addressed in #144, but more room for improvement.

**Comment by Bhavin789** [comment]
Hello @noway, I can try to have a look at few areas of the code to see where can it be improved. I might not be able to check all at once but, maybe one at a time? Let me know if that sounds ok. Thanks!

**Comment by noway** [comment]
@Bhavin789 yes please do!

**Comment by noway** [comment]
This has been less of an issue recently, so closing.
