### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by noway** [vaxxnz/vaxxnz#241]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when users are asking frequently asked questions

**Describe the solution you'd like**
An FAQ page

**Additional context**
questions:

> How do I get my location listed?

Contact Healthpoint

**Comment by rodrigohdiaz** [comment]
@olafwrieden yes, I can work on this one unless anyone else is already working on it

**Comment by olafwrieden** [comment]
> @olafwrieden yes, I can work on this one unless anyone else is already working on it

Go for it!

**Comment by rodrigohdiaz** [comment]
@olafwrieden question, is there any text for the frequently asked questions for me to add there?

**Comment by olafwrieden** [comment]
> @olafwrieden question, is there any text for the frequently asked questions for me to add there?

Please ask this in the dev channel on Discord. Things like: How often does the data refresh? How can I share it with others? How do I contribute etc..

**Comment by noway** [comment]
We now have a small FAQ

**Comment by noway** [comment]
Would love to extend our FAQ with more info though! So open to making a new issue to extend our FAQ
