### ISSUE TITLE
Available label is not properly aligned on Safari

### ISSUE THREAD

**Issue by noway** [vaxxnz/vaxxnz#254]
**Describe the bug**
Available label is not properly aligned on Safari

**To Reproduce**

1. Go to vaxx.nz on Safari
2. Observer Available label not properly aligned

**Screenshots**
safari:
![image](https://user-images.githubusercontent.com/2031472/134315984-4237301d-8e8f-4f74-bef8-593cbfe6eb45.png)
chrome:
![image](https://user-images.githubusercontent.com/2031472/134316026-0f10a14a-61d7-4127-a1ae-e2e436e83e64.png)

**Device:**

- Device: Mac OS Big Sur
- Browser: Safari

**Additional context**
Not sure what's going on, I couldn't figure it out

**Comment by noway** [comment]
Props to @keison-tang for solving this! 🙏🏻

**Comment by keison-tang** [comment]
Just noticed the same issue for walk-in opening times on Safari, reopen the issue and I'll make another PR 😊

**Comment by noway** [comment]
Oh good catch, please do! 🙏

**Comment by noway** [comment]
This has been resolved
