### ISSUE TITLE
Cancel button on `HealthpointModal` is misleading

### ISSUE THREAD

**Issue by CoderYihaoWang** [vaxxnz/vaxxnz#310]
**Describe the bug**

Please see the screenshot. The "Cancel" button (outlined) is misleading, especially when it is translated into other languages e.g. Chinese.

Clicking on this "Cancel" button, we will be redirected to the walk-in locations page. So here "Cancel" means "Go back" which kind of makes sense in English.

However, the i18n key is defined as `walkins.cancelBooking`. So, translations including Chinese put the equivalent of "Cancel Booking" on this button ("取消预约"). This is not what this button actaully does.

To make it more confusing, notice that on the left hand side, there is a message telling people "Remember to cancel your original booking if you....." So, in this context, people will likely to think that if you click on that button, you will be redirected to a page where you can cancel your previous booking for this location.

**To Reproduce**
1. Go to the "walk-in" tab
2. Choose any one of the locations. 
3. Observe the "Cancel" button.

**Screenshots**
![cancel-booking](https://user-images.githubusercontent.com/48015192/136016346-f4be8e96-5577-4b34-b10e-8767807468c8.png)

**Device:**

**Additional context**

To reduce potential confusion, I think at least the translations should be updated, from the equivalent of "Cancel Booking" to just "Cancel" or simply "Back". But to keep things consistent, perhaps it is better that we also change the i18n key for this to `walkins.cancel` or `walkins.back` so that it does not confuse translaters.

**Comment by CoderYihaoWang** [comment]
I can submit a PR to update the Chinese translations as well as update the i18n key to `walkins.back` (what do you think?) But we'll need others' help to update the translations to other languages : )

**Comment by noway** [comment]
This has been addressed!
