### ISSUE TITLE
Last updated is a long time ago (Months)

### ISSUE THREAD

**Issue by sleemanj** [vaxxnz/vaxxnz#334]
**Describe the bug**
I don't know if this is normal, but I thought the last updated would be ~every 30 minutes, but locations are reporting last updated several months ago.

**To Reproduce**
Open site, look at last updated.

**Screenshots**
![lu](https://user-images.githubusercontent.com/207209/152437426-45dead53-3525-47d4-811b-85d0b57ed880.jpg)

**Device:**

98.0.4758.66 (Official Build) beta (64-bit) 

**Additional context**

**Comment by sleemanj** [comment]
404's from githubusercontent

![lu1](https://user-images.githubusercontent.com/207209/152438445-599e1007-7f87-40f8-96e8-7927f3c66d35.jpg)

**Comment by waltzaround** [comment]
Investigating after work today - please hold caller

**Comment by noway** [comment]
The `node ./lib/availability.js` job got stuck. I killed the process. The job restarted and the availability scraping continued as normal.

I've added a cronjob which fires off at 02:15AM every day to kill `node ./lib/availability.js` job just in case.

It would be nice to add [monitoring](https://github.com/vaxxnz/vaxxnzlocations/issues/17) at some point in the future.
